name: CI/CD Workflow for Java Tests

on:
  workflow_dispatch:
    inputs:
      runs_on:
        required: true
        default: windows-latest
        description: Select virtual machine in which test will be run
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest

# Git trigger
#on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  test:

    runs-on: ${{github.event.inputs.runs_on}}

    steps:
      # You may pin to the exact commit or the version.
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Edge
      # uses: browser-actions/setup-edge@5a55d8fc0f012aa6e16b582df5bf9d6274bda7da
        uses: browser-actions/setup-edge@v1.1.1
        with:
        # The Edge version to be installed.  Supported versions are "stable", "beta", "dev". Optional
          edge-version: stable

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      # Run Maven to install dependencies and execute tests
      - name: Run Tests with Maven
        run: |
          mvn clean test

      # Upload multiple Extent HTML reports as artifacts
      - name: Upload all Extent HTML reports
        if: failure() || success()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: ./test-output/ExtentReport.html  # Adjust the path to match where reports are saved
